config/routes.rb
WellnessTracker::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "pages#index"

  resources :activity_logs do
    member do
      get 'copy'
      post 'create_copy'
    end
  end

  resources :teams do
    member do
      post 'join'
      post 'leave'
      post 'lead'
    end
  end
  
  get '/leaderboard' => 'pages#leaderboard'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :category
	has_many :activity_records
	validates :category_id, presence: true
end

app/models/activity_log.rb
class ActivityLog < ActiveRecord::Base
	belongs_to :user
	has_many :activity_records, dependent: :destroy
	has_many :activities, through: :activity_records
	accepts_nested_attributes_for :activity_records
	validates :date, presence: :true
	validates :date, uniqueness: { scope: :user_id,
    message: "must be unique" }

	def points
		self.activity_records.collect {|x| x.activity.points}.reduce(:+)
	end

	def create_records(activsparams)
		#activity parameters in form of ["", "2", "9", "", "6", "", "8"]. below is a workaround, figure out how to fix form
		actstolog = activsparams.select{|s| s.size > 0}.map{|s| s.to_i}
		actstolog.each {|activity| 
		self.activity_records.new("activity_id" => activity)}
	end

end

app/models/activity_record.rb
class ActivityRecord < ActiveRecord::Base
  belongs_to :activity
  belongs_to :activity_log
  belongs_to :user
  #validates :activity_log_id, presence: true
  validates :activity_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :activities
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :team_memberships, dependent: :destroy
	has_many :users, through: :team_memberships
	validates_associated :team_memberships

	def score
		self.users.collect{|u| u.score}.reduce(:+) || 0
	end

	def captain
		captaincy = (self.team_memberships.find_by :captain => true)
		if captaincy.nil?
			"None" 
		else captaincy.user.username
		end
	end
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  validates :user_id, uniqueness: {message: "can only belong to one team"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :team_membership
  has_one :team, through: :team_membership

  has_many :activity_logs
  has_many :activity_records, through: :activity_logs

  validates :namefirst, :namelast, :username, presence: :true

  def score
  	self.activity_records.collect {|x| x.activity.points}.reduce(:+) || 0
  end
  
end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
	before_filter :find_log, :only => [:copy, :show, :destroy, :edit, :update]
	before_filter :setup_activities_and_categories, :only => [:copy, :edit, :new, :create]

def index
	@activity_logs = ActivityLog.where(:user => current_user).order(date: :desc).page(params[:page]).per(10)
end

def new
	@activity_log = ActivityLog.new
	@activity_records = @activity_log.activity_records.build
end

def create
	@activity_log = ActivityLog.new(activity_log_params)
	@activity_log.user = current_user
	@activity_log.create_records(params[:activity_log][:activity_ids])
		if @activity_log.save
			redirect_to activity_logs_path
		else flash.now[:alert] = @activity_log.errors.full_messages.to_sentence
		render "new"
		end
end

def show
end

def destroy
	@activity_log.destroy
	redirect_to activity_logs_path
end

def edit
end

def update
	@activity_log.update(activity_log_params)
	@activity_log.activity_records.destroy_all
	@activity_log.create_records(params[:activity_log][:activity_ids])
		if @activity_log.save
			redirect_to activity_logs_path
		else flash.now[:alert] = "Could not save"
		render "new"
		end
end

def copy
end

	private

	def activity_log_params
		params.require(:activity_log).permit(:date, :user_id, :activity_records_attributes => [:activity_id => []])
	end

	def find_log
		@activity_log = ActivityLog.find(params[:id])
	end

	def setup_activities_and_categories
		@activities = Activity.order(title: :asc)
		@categories = Category.order(title: :asc)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
 
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def leaderboard
		@users = User.joins(:activity_logs).uniq
		@teams = Team.all
		@scoreshash = Hash[@users.map{|user| [user.username, user.score]}]
		@teamscores = Hash[@teams.map{|team| [team.name, team.score]}] 
	end

	def index
		@user = current_user
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@teams = Team.all
	end

	def show
		@team = Team.find(params[:id])
		@members = @team.users
	end

	def new
		@team = Team.new
	end

	def create
		@user = current_user
		@team = Team.new(team_params)
		@team.team_memberships.build(:user_id => @user.id, :captain => true)
		if @team.save
			redirect_to teams_path
		else flash.now[:alert] = @team.errors.full_messages.to_sentence
		render "new"
		end
	end

	def join
		@team = Team.find(params[:id])
		@members = @team.users
		membership = @team.team_memberships.new(:user => current_user)
		if membership.save
			redirect_to team_path(@team)
		else
			flash.now[:alert] = membership.errors.full_messages.to_sentence
		render "show"
		end
	end

	def leave
		@team = Team.find(params[:id])
		@members = @team.users
		membership = @team.team_memberships.find_by(:user => current_user)
		if membership.destroy
			redirect_to team_path(@team)
		else
			flash.now[:alert] = membership.errors.full_messages.to_sentence
		render "show"
		end
	end

	def lead
		@team = Team.find(params[:id])
		@members = @team.users
		membership = @team.team_memberships.find_by(:user => current_user)
		membership.captain = true
		if membership.save
			redirect_to team_path(@team)
		else
			flash.now[:alert] = membership.errors.full_messages.to_sentence
		render "show"
		end
	end

private

	def team_params
		params.require(:team).permit(:name)
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_log_helper.rb
module ActivityLogHelper
end

app/helpers/activityrecords_helper.rb
module ActivityrecordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/activity_logs/_form.html.erb
<%= simple_form_for(@activity_log) do |f| %>
<%= f.input :date, :value => Date.today %>
	<% @categories.each do |category| %>
	<%= f.association :activities, collection: @activities.select{|a| a.category_id == category.id}, label: "#{category.title}", :input_html => {"multiple" => "multiple"}%>
	<% end %>

<%= f.submit 'Save Log', {:class => "btn btn-primary"} %>

<% end %>

app/views/activity_logs/copy.html.erb
<h1>Copy Log</h1>
<%= simple_form_for @activity_log, :url => {:action => "create"},:method => :POST do |f| %>
<%= f.input :date, :value => Date.today %>
	<% @categories.each do |category| %>
	<%= f.association :activities, collection: @activities.select{|a| a.category_id == category.id}, label: "#{category.title}", :input_html => {"multiple" => "multiple"}%>
	<% end %>

<%= f.submit 'Save Log', {:class => "btn btn-primary"} %>

<% end %>

app/views/activity_logs/edit.html.erb
<h1>Edit Log</h1>
<%= render "form" %>

app/views/activity_logs/index.html.erb
<h1>My Logs</h1>
<div class = "row">
      <div class = "col-md-12 col-lg-6">
<% if @activity_logs.count > 0 %>
<table class="table table-condense table-hover">
	<thead>
		<tr>
			<th>Date</th>
			<th>Points</th>
		</tr>
	</thead>
<% @activity_logs.each do |log| %>
<tr>
<td><%= log.date.strftime('%m/%d/%Y') %></td>
<td><%= log.points %></td>
<td><%= link_to activity_log_path(log.id), class: "btn btn-default btn-sm hidden-xs" do %>
    <span class="glyphicon glyphicon-list"></span> Show
	<% end %></td>
<td><%= link_to edit_activity_log_path(log.id), class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-pencil"></span> Edit
	<% end %></td>	
<td><%= link_to copy_activity_log_path(log.id), class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-share"></span> Copy
	<% end %></td>
<td><%= link_to log, {:method => "delete", :class => "btn btn-default btn-sm hidden-xs", data: { confirm: 'Are you sure?' }} do %>
    <span class="glyphicon glyphicon-remove"></span> Delete
	<% end %></td>
<% end %>
</table>
<%= paginate @activity_logs %>
<% else %>
<p>No Logs Found</p>
<% end %>

</div>
    </div>

<%= button_to "Log Daily Points", new_activity_log_path, {:method => "get", :class => "btn btn-primary"} %>


app/views/activity_logs/new.html.erb
<%= simple_form_for(@activity_log) do |f| %>
<%= f.text_field :date, :id => "datepicker", :value => Date.today %>
	<% @categories.each do |category| %>
	<%= f.association :activities, collection: @activities.select{|a| a.category_id == category.id}, label: "#{category.title}" %>
	<% end %>

<%= f.submit 'Log Activity', {:class => "btn btn-primary"} %>
<% end %>

<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd', todayHighlight: true});
</script>

app/views/activity_logs/show.html.erb
<h1>Log Detail</h1>
<p><b>Date: </b><%= @activity_log.date %></p>
<table class="table table-condensed">
	<thead>
		<tr>
			<th>Activity</th>
			<th>Points</th>
		</tr>
	</thead>
<tbody>
<% @activity_log.activity_records.each do |record| %>
<tr>
<td><%= record.activity.title %></td>
<td><%= record.activity.points %></td>
</tr>
<% end %>
</tbody>
</table>
<%= button_to "Edit log", edit_activity_log_path, {:method => "get", :class => "btn btn-primary"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wellness Tracker</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>


    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

 <% unless notice.nil? %>
 <p class="alert alert-info"><%= notice %></p>
 <% end %>
 <%unless alert.nil? %>
   <p class="alert alert-danger"><%= alert %></p>
 <% end %>

<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Wellness Tracker</a>
    </div>
    <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><a href="/">Home</a></li>
      <% if user_signed_in? %>
      <li>
        <%= link_to "Log Now!", new_activity_log_path %>
       </li>
      <li>
        <%= link_to "My Logs", activity_logs_path %>
       </li>
         <li>
        <%= link_to "Leaderboard", leaderboard_path %>
       </li>
        <li>
        <%= link_to "Teams", teams_path %>
       </li>
       <% end %>
    </ul>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path %>| <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></p>
      <% else %>
      <%= link_to "Sign In", new_user_session_path %> | <%= link_to "Sign Up!", new_user_registration_path %></p> 
      <% end %>      
  </div>
  </div>
</div>
</head>

<body>

  <div class = "container">
    
 
<%= yield %>
      
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron text-center">
	<h1>Wellness Tracker</h1>
	<p>[for complicated wellness competitions]</p>
	<% if user_signed_in? && @user.admin? %>
	<h6><%= link_to "Competition Admin", rails_admin.dashboard_path %> </h6>
	<% end %>
</div>


app/views/pages/leaderboard.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class = "active"><a href="#individual" role="tab">Individual</a></li>
  <li role="presentation"><a href="#team" role="tab">Team</a></li>
</ul>

<div class = "tab-content">
	<div class = "tab-pane active" id="individual"><%= column_chart @scoreshash %></div>
	<div class = "tab-pane" id="team"><%= column_chart @teamscores %></div>
</div>